import type { Exercise, Measure } from './types'

type Row = [name: string, muscles: string, measure?: Measure]

const groups: Record<string, Row[]> = {
  Push: [
    ['Push-up', 'Chest, triceps, shoulders'],
    ['Knee Push-up', 'Chest, triceps, shoulders'],
    ['Incline Push-up', 'Chest, triceps, shoulders'],
    ['Decline Push-up', 'Upper chest, shoulders, triceps'],
    ['Diamond Push-up', 'Triceps, chest'],
    ['Wide Push-up', 'Chest, shoulders'],
    ['Archer Push-up', 'Chest, triceps, shoulders'],
    ['Pseudo Planche Push-up', 'Shoulders, chest, triceps'],
    ['One-arm Push-up', 'Chest, triceps, core'],
    ['Pike Push-up', 'Shoulders, triceps'],
    ['Elevated Pike Push-up', 'Shoulders, triceps'],
    ['Wall Handstand Push-up', 'Shoulders, triceps'],
    ['Handstand Push-up', 'Shoulders, triceps'],
    ['Bench Dip', 'Triceps, chest'],
    ['Parallel Bar Dip', 'Chest, triceps, shoulders'],
    ['Ring Dip', 'Chest, triceps, shoulders'],
    ['Straight Bar Dip', 'Chest, triceps, shoulders'],
    ['Ring Push-up', 'Chest, triceps, core'],
  ],
  Pull: [
    ['Pull-up', 'Lats, biceps, upper back'],
    ['Chin-up', 'Biceps, lats'],
    ['Neutral-grip Pull-up', 'Lats, biceps'],
    ['Wide-grip Pull-up', 'Lats, upper back'],
    ['Negative Pull-up', 'Lats, biceps'],
    ['Band-assisted Pull-up', 'Lats, biceps'],
    ['Archer Pull-up', 'Lats, biceps'],
    ['Typewriter Pull-up', 'Lats, biceps'],
    ['L-sit Pull-up', 'Lats, biceps, core'],
    ['Explosive Pull-up', 'Lats, biceps'],
    ['Muscle-up', 'Lats, chest, triceps'],
    ['Ring Muscle-up', 'Lats, chest, triceps'],
    ['Australian Row', 'Upper back, biceps'],
    ['Ring Row', 'Upper back, biceps'],
    ['Front Lever Row', 'Lats, core'],
    ['Scapular Pull-up', 'Lower traps, lats'],
    ['Dead Hang', 'Grip, shoulders', 'seconds'],
    ['Active Hang', 'Grip, lats, scapulae', 'seconds'],
  ],
  Legs: [
    ['Bodyweight Squat', 'Quads, glutes'],
    ['Jump Squat', 'Quads, glutes, calves'],
    ['Split Squat', 'Quads, glutes'],
    ['Bulgarian Split Squat', 'Quads, glutes'],
    ['Walking Lunge', 'Quads, glutes'],
    ['Reverse Lunge', 'Quads, glutes'],
    ['Step-up', 'Quads, glutes'],
    ['Cossack Squat', 'Adductors, quads, glutes'],
    ['Shrimp Squat', 'Quads, glutes'],
    ['Pistol Squat', 'Quads, glutes, balance'],
    ['Box Pistol Squat', 'Quads, glutes'],
    ['Sissy Squat', 'Quads'],
    ['Nordic Curl', 'Hamstrings'],
    ['Glute Bridge', 'Glutes, hamstrings'],
    ['Single-leg Glute Bridge', 'Glutes, hamstrings'],
    ['Hip Thrust', 'Glutes'],
    ['Calf Raise', 'Calves'],
    ['Single-leg Calf Raise', 'Calves'],
    ['Wall Sit', 'Quads', 'seconds'],
  ],
  Core: [
    ['Plank', 'Core', 'seconds'],
    ['Side Plank', 'Obliques', 'seconds'],
    ['Hollow Body Hold', 'Core', 'seconds'],
    ['Arch Hold', 'Lower back, glutes', 'seconds'],
    ['Crunch', 'Abs'],
    ['Sit-up', 'Abs, hip flexors'],
    ['Lying Leg Raise', 'Lower abs, hip flexors'],
    ['Hanging Knee Raise', 'Abs, hip flexors'],
    ['Hanging Leg Raise', 'Abs, hip flexors'],
    ['Toes-to-bar', 'Abs, hip flexors, lats'],
    ['Windshield Wiper', 'Obliques, abs'],
    ['Dragon Flag', 'Abs, core'],
    ['Ab Wheel Rollout', 'Abs, core'],
    ['V-up', 'Abs'],
    ['Russian Twist', 'Obliques'],
    ['Mountain Climber', 'Core, hip flexors'],
    ['Dead Bug', 'Core'],
  ],
  Skills: [
    ['L-sit', 'Core, hip flexors, triceps', 'seconds'],
    ['Tuck L-sit', 'Core, hip flexors', 'seconds'],
    ['V-sit', 'Core, hip flexors', 'seconds'],
    ['Crow Pose', 'Wrists, shoulders, core', 'seconds'],
    ['Wall Handstand', 'Shoulders, core', 'seconds'],
    ['Freestanding Handstand', 'Shoulders, core, balance', 'seconds'],
    ['Tuck Front Lever', 'Lats, core', 'seconds'],
    ['Advanced Tuck Front Lever', 'Lats, core', 'seconds'],
    ['Straddle Front Lever', 'Lats, core', 'seconds'],
    ['Front Lever', 'Lats, core', 'seconds'],
    ['Tuck Back Lever', 'Shoulders, chest, core', 'seconds'],
    ['Back Lever', 'Shoulders, chest, core', 'seconds'],
    ['Planche Lean', 'Shoulders, wrists', 'seconds'],
    ['Tuck Planche', 'Shoulders, core', 'seconds'],
    ['Straddle Planche', 'Shoulders, core', 'seconds'],
    ['Human Flag', 'Obliques, shoulders, lats', 'seconds'],
    ['Skin the Cat', 'Shoulders, lats'],
    ['Support Hold', 'Triceps, shoulders', 'seconds'],
  ],
  Conditioning: [
    ['Burpee', 'Full body'],
    ['Jumping Jack', 'Full body'],
    ['Bear Crawl', 'Shoulders, core', 'seconds'],
    ['High Knees', 'Legs, cardio', 'seconds'],
    ['Jump Rope', 'Calves, cardio', 'seconds'],
    ['Broad Jump', 'Legs, power'],
  ],
}

const slug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-')

export const LIBRARY: Exercise[] = Object.entries(groups).flatMap(([category, rows]) =>
  rows.map(([name, muscles, measure = 'reps']) => ({
    id: `lib-${slug(name)}`,
    name,
    category,
    muscles,
    measure,
    custom: false,
  })),
)
