import type { Equipment, Exercise, Measure, Pattern } from './types'

/**
 * name, muscles, movement pattern (null = not used by the generator), difficulty step 1–5,
 * equipment (any one of them is enough; empty = none needed), measure.
 */
type Row = [name: string, muscles: string, pattern: Pattern | null, level: number, equipment: Equipment[], measure?: Measure]

const groups: Record<string, Row[]> = {
  Push: [
    ['Push-up', 'Chest, triceps, shoulders', 'hpush', 2, []],
    ['Knee Push-up', 'Chest, triceps, shoulders', 'hpush', 1, []],
    ['Incline Push-up', 'Chest, triceps, shoulders', 'hpush', 1, []],
    ['Decline Push-up', 'Upper chest, shoulders, triceps', 'hpush', 3, []],
    ['Diamond Push-up', 'Triceps, chest', 'hpush', 3, []],
    ['Wide Push-up', 'Chest, shoulders', 'hpush', 2, []],
    ['Archer Push-up', 'Chest, triceps, shoulders', 'hpush', 4, []],
    ['Pseudo Planche Push-up', 'Shoulders, chest, triceps', 'hpush', 4, []],
    ['One-arm Push-up', 'Chest, triceps, core', 'hpush', 5, []],
    ['Pike Push-up', 'Shoulders, triceps', 'vpush', 2, []],
    ['Elevated Pike Push-up', 'Shoulders, triceps', 'vpush', 3, []],
    ['Wall Handstand Push-up', 'Shoulders, triceps', 'vpush', 4, []],
    ['Handstand Push-up', 'Shoulders, triceps', 'vpush', 5, []],
    ['Bench Dip', 'Triceps, chest', 'vpush', 1, []],
    ['Negative Dip', 'Chest, triceps, shoulders', 'vpush', 2, ['dip']],
    ['Parallel Bar Dip', 'Chest, triceps, shoulders', 'vpush', 3, ['dip']],
    ['Russian Dip', 'Triceps, chest, shoulders', 'vpush', 4, ['dip']],
    ['Ring Dip', 'Chest, triceps, shoulders', 'vpush', 4, ['rings']],
    ['Straight Bar Dip', 'Chest, triceps, shoulders', 'vpush', 4, ['bar']],
    ['Ring Push-up', 'Chest, triceps, core', 'hpush', 3, ['rings']],
  ],
  Pull: [
    ['Pull-up', 'Lats, biceps, upper back', 'vpull', 3, ['bar']],
    ['Chin-up', 'Biceps, lats', 'vpull', 3, ['bar']],
    ['Neutral-grip Pull-up', 'Lats, biceps', 'vpull', 3, ['bar']],
    ['Wide-grip Pull-up', 'Lats, upper back', 'vpull', 4, ['bar']],
    ['Negative Pull-up', 'Lats, biceps', 'vpull', 2, ['bar']],
    ['Band-assisted Pull-up', 'Lats, biceps', 'vpull', 2, ['bar']],
    ['Archer Pull-up', 'Lats, biceps', 'vpull', 5, ['bar']],
    ['Typewriter Pull-up', 'Lats, biceps', 'vpull', 5, ['bar']],
    ['L-sit Pull-up', 'Lats, biceps, core', 'vpull', 4, ['bar']],
    ['Explosive Pull-up', 'Lats, biceps', 'vpull', 4, ['bar']],
    ['Muscle-up', 'Lats, chest, triceps', 'skill', 5, ['bar']],
    ['Ring Muscle-up', 'Lats, chest, triceps', 'skill', 5, ['rings']],
    ['Australian Row', 'Upper back, biceps', 'hpull', 2, ['bar', 'dip']],
    ['Ring Row', 'Upper back, biceps', 'hpull', 2, ['rings']],
    ['Feet-elevated Ring Row', 'Upper back, biceps', 'hpull', 3, ['rings']],
    ['Archer Ring Row', 'Upper back, biceps', 'hpull', 4, ['rings']],
    ['Front Lever Row', 'Lats, core', 'hpull', 5, ['bar', 'rings']],
    ['Scapular Pull-up', 'Lower traps, lats', 'warmup', 1, ['bar']],
    ['Dead Hang', 'Grip, shoulders', null, 1, ['bar'], 'seconds'],
    ['Active Hang', 'Grip, lats, scapulae', 'warmup', 1, ['bar'], 'seconds'],
  ],
  Legs: [
    ['Bodyweight Squat', 'Quads, glutes', 'squat', 1, []],
    ['Jump Squat', 'Quads, glutes, calves', 'squat', 2, []],
    ['Split Squat', 'Quads, glutes', 'lunge', 1, []],
    ['Bulgarian Split Squat', 'Quads, glutes', 'lunge', 3, []],
    ['Walking Lunge', 'Quads, glutes', 'lunge', 2, []],
    ['Reverse Lunge', 'Quads, glutes', 'lunge', 2, []],
    ['Step-up', 'Quads, glutes', 'lunge', 1, []],
    ['Cossack Squat', 'Adductors, quads, glutes', 'squat', 3, []],
    ['Shrimp Squat', 'Quads, glutes', 'squat', 4, []],
    ['Pistol Squat', 'Quads, glutes, balance', 'squat', 5, []],
    ['Box Pistol Squat', 'Quads, glutes', 'squat', 4, []],
    ['Sissy Squat', 'Quads', 'squat', 3, []],
    ['Nordic Curl', 'Hamstrings', 'hinge', 5, []],
    ['Glute Bridge', 'Glutes, hamstrings', 'hinge', 1, []],
    ['Single-leg Glute Bridge', 'Glutes, hamstrings', 'hinge', 2, []],
    ['Hip Thrust', 'Glutes', 'hinge', 2, []],
    ['Single-leg Romanian Deadlift', 'Hamstrings, glutes, balance', 'hinge', 3, []],
    ['Calf Raise', 'Calves', null, 1, []],
    ['Single-leg Calf Raise', 'Calves', null, 2, []],
    ['Wall Sit', 'Quads', null, 1, [], 'seconds'],
  ],
  Core: [
    ['Plank', 'Core', 'core', 1, [], 'seconds'],
    ['Side Plank', 'Obliques', 'core', 1, [], 'seconds'],
    ['Hollow Body Hold', 'Core', 'core', 2, [], 'seconds'],
    ['Arch Hold', 'Lower back, glutes', 'core', 1, [], 'seconds'],
    ['Crunch', 'Abs', 'core', 1, []],
    ['Sit-up', 'Abs, hip flexors', 'core', 1, []],
    ['Lying Leg Raise', 'Lower abs, hip flexors', 'core', 2, []],
    ['Hanging Knee Raise', 'Abs, hip flexors', 'core', 2, ['bar']],
    ['Hanging Leg Raise', 'Abs, hip flexors', 'core', 3, ['bar']],
    ['Dip Bar Knee Raise', 'Abs, hip flexors', 'core', 2, ['dip']],
    ['Dip Bar Leg Raise', 'Abs, hip flexors', 'core', 3, ['dip']],
    ['Toes-to-bar', 'Abs, hip flexors, lats', 'core', 4, ['bar']],
    ['Windshield Wiper', 'Obliques, abs', 'core', 5, ['bar']],
    ['Dragon Flag', 'Abs, core', 'core', 5, []],
    ['Ab Wheel Rollout', 'Abs, core', null, 3, []],
    ['V-up', 'Abs', 'core', 2, []],
    ['Russian Twist', 'Obliques', 'core', 1, []],
    ['Mountain Climber', 'Core, hip flexors', null, 1, []],
    ['Dead Bug', 'Core', 'core', 1, []],
  ],
  Skills: [
    ['L-sit', 'Core, hip flexors, triceps', 'skill', 3, ['dip'], 'seconds'],
    ['Tuck L-sit', 'Core, hip flexors', 'skill', 2, ['dip'], 'seconds'],
    ['V-sit', 'Core, hip flexors', 'skill', 5, [], 'seconds'],
    ['Crow Pose', 'Wrists, shoulders, core', 'skill', 1, [], 'seconds'],
    ['Wall Handstand', 'Shoulders, core', 'skill', 2, [], 'seconds'],
    ['Freestanding Handstand', 'Shoulders, core, balance', 'skill', 4, [], 'seconds'],
    ['Tuck Front Lever', 'Lats, core', 'skill', 2, ['bar', 'rings'], 'seconds'],
    ['Advanced Tuck Front Lever', 'Lats, core', 'skill', 3, ['bar', 'rings'], 'seconds'],
    ['Straddle Front Lever', 'Lats, core', 'skill', 4, ['bar', 'rings'], 'seconds'],
    ['Front Lever', 'Lats, core', 'skill', 5, ['bar', 'rings'], 'seconds'],
    ['Tuck Back Lever', 'Shoulders, chest, core', 'skill', 2, ['bar', 'rings'], 'seconds'],
    ['Back Lever', 'Shoulders, chest, core', 'skill', 4, ['bar', 'rings'], 'seconds'],
    ['Planche Lean', 'Shoulders, wrists', 'skill', 1, [], 'seconds'],
    ['Tuck Planche', 'Shoulders, core', 'skill', 3, ['dip'], 'seconds'],
    ['Straddle Planche', 'Shoulders, core', 'skill', 5, ['dip'], 'seconds'],
    ['Human Flag', 'Obliques, shoulders, lats', 'skill', 5, ['bar'], 'seconds'],
    ['Skin the Cat', 'Shoulders, lats', 'skill', 2, ['rings', 'bar']],
    ['Support Hold', 'Triceps, shoulders', 'skill', 1, ['dip', 'rings'], 'seconds'],
    ['Ring Support Hold', 'Triceps, shoulders, stability', 'skill', 2, ['rings'], 'seconds'],
  ],
  'Warm-up': [
    ['Band Pull-apart', 'Rear delts, upper back', 'warmup', 1, ['band']],
    ['Band Dislocate', 'Shoulders, mobility', 'warmup', 1, ['band']],
    ['Band External Rotation', 'Rotator cuff', 'warmup', 1, ['band']],
    ['Band Face Pull', 'Rear delts, rotator cuff', 'warmup', 1, ['band']],
    ['Banded Glute Bridge', 'Glutes', 'warmup', 1, ['band']],
    ['Banded Squat', 'Quads, glutes, hips', 'warmup', 1, ['band']],
    ['Wrist Circles', 'Wrists', 'warmup', 1, [], 'seconds'],
    ['Arm Circles', 'Shoulders', 'warmup', 1, [], 'seconds'],
    ['Cat-Cow', 'Spine mobility', 'warmup', 1, []],
    ['Scapular Push-up', 'Serratus, scapulae', 'warmup', 1, []],
  ],
  Conditioning: [
    ['Burpee', 'Full body', null, 2, []],
    ['Jumping Jack', 'Full body', null, 1, []],
    ['Bear Crawl', 'Shoulders, core', null, 1, [], 'seconds'],
    ['High Knees', 'Legs, cardio', null, 1, [], 'seconds'],
    ['Jump Rope', 'Calves, cardio', null, 1, [], 'seconds'],
    ['Broad Jump', 'Legs, power', null, 2, []],
  ],
}

const slug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-')

export const LIBRARY: Exercise[] = Object.entries(groups).flatMap(([category, rows]) =>
  rows.map(([name, muscles, pattern, level, equipment, measure = 'reps']) => ({
    id: `lib-${slug(name)}`,
    name,
    category,
    muscles,
    measure,
    custom: false,
    pattern,
    level,
    equipment,
  })),
)
